name: Check for soon-to-expire service principal secrets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *' # 17:00 CEST / 16:00 CET

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Check for soon-to-expire service principal secrets
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm
      - name: Check for soon-to-expire service principal secrets
        run: npm run start
        env:
          DAY_UNTIL_EXPIRATION: 60